### PR TITLE
Implement custom tint color for navigation & loading bars

### PR DESCRIPTION
**Pull request by skycocker**

### CODE REVIEW

**Comment by yannickoo** [comment]
Oh nice! Thank you for that pull request, works pretty fine but I would suggest to add `processColor` function to the `README.md` otherwise it's hard for users to find where this comes from.

It seems like we can open another pull request [soon](https://github.com/TimOliver/TOWebViewController/pull/95) for implementing the color of the `Done` button :)

**Comment by mfkp** [comment]
Thanks for adding @skycocker - testing it out now.

**Comment by mfkp** [comment]
Thanks for the implementation @skycocker, looks like it's working fine.

@yannickoo good idea, I updated the code sample with `processColor` details. Looking forward to being able to customize that done button color :-)

**Comment by skycocker** [comment]
@yannickoo, @mfkp - all it would take to customize done button is to update `TOWebViewController` submodule version.

**Comment by mfkp** [comment]
@skycocker I only see options for `showDoneButton` and `doneButtonTitle` right now:
[TOWebViewController.h](https://github.com/TimOliver/TOWebViewController/blob/master/TOWebViewController/TOWebViewController.h)

If/when [this PR](https://github.com/TimOliver/TOWebViewController/pull/95) gets merged, I can update the submodule, but I'd rather not link it to that person's fork.

**Comment by mfkp** [comment]
Oh nevermind, I see that in the current version, it copies the color from the bottom buttons: https://github.com/TimOliver/TOWebViewController/blob/master/TOWebViewController/TOWebViewController.m#L352

I'll push out an updated version with that change.

**Comment by mfkp** [comment]
FYI v0.6.2 has been pushed out with the updated TOWebViewController

**Pull request merged**
